name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.5'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run React tests
        run: npm run test -- --coverage --watch=false

      - name: Build Project for Distribution
        run: npm run build
